### ISSUE TITLE
edb live ebuild dependencies

### ISSUE THREAD

**Issue by eteran** [Petross404/local#1]
Saw some quirks in the `RDEPEND` section of the edb live ebuild, though they could be cleaned up:

1. doxygen is not a required to build edb. We actually don't use doxygen docs
2. freetype, openssl, libbsd, glib , libxshmfence are perhaps indirect dependencies (not sure), but I see no reason to include them in the list since they would get pulled in by things which depend on them directly.
3. the version of boost isn't correct. You have ` >=dev-libs/boost-1.3.5`, it should be ` >=dev-libs/boost-1.35.0`
4. probably should add `dev-qt/qtnetwork` to the list, the version checker plugin depends on it.
5. I think that technically `dev-util/cmake` and `dev-libs/boost` belong in `DEPEND` but not `RDEPEND`. My understanding is that `RDEPEND` is for runtime dependencies and `DEPEND` is for compile time dependencies.

Thanks so much for your efforts!

**Comment by eteran** [comment]
Looks like you've addressed all 5 of these in the latest version of the ebuild!
Thanks, looks awesome :-)

**Comment by Petross404** [comment]
I saw this last afternoon and didn't reply because I wanted to solve once and for all the menu entry problem. I think I am gonna use `sed` in order to disable the installation of your .desktop file. Not that it is bad, the only way to create a menu entry is with `make_desktop_entry` which creates **and** a .desktop file. 

Something doesn't feel rigth, but for the moment I am just use basic features of `sed` and that's all. I would be more that happy to see someone's modification in the future.

Something else that I forget to propose: As a Gentoo user yourself, you know that live (-9999) packages are hard-masked. Should a version be created (like 0.9.blah.tar.xz or something) in order to be keyword-masked (~amd64) so that users aren't hesitant if to try a live, hard-masked package?

If any bug reports occur, I guess it's your email address that these reports  will be sent. I would like to help though with ebuild-specific problems though (of course) - it's just I don't know **that** much of programming and especially about your software. :)

**Comment by Petross404** [comment]
If only sed was that easy. It wouldn't replace that specific "install" entry no matter what... Anyway I created a patch for CMakeLists.txt and now only one .desktop file is installed. Although it is named as edb-edb.desktop which I find it wrong, at least a proper menu entrry exists.

I noticed this error: 
` * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /usr/include/bits/string3.h:53:71: warning: call to void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int) will always overflow destination buffer

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://github.com/eteran/edb-debugger
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -R .comment -R .GCC.command.line -R .note.gnu.gold-version
`

It comes up _just_ before installing. Please let me know if it worth opening another issue for it.
Just in case you want to email me : petross404@gmail.com
